# fly.toml app configuration file generated for ritibot on 2023-04-20T18:37:13-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ritibot"
primary_region = "gru"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "paketobuildpacks/builder:base"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [services.concurrency]
	hard_limit = 25
	soft_limit = 20

  [[services.ports]]
	handlers = ["http"]
	port = "80"

  [[services.ports]]
	handlers = ["tls", "http"]
	port = "443"

  [[services.tcp_checks]]
	grace_period = "1s"
	interval = "15s"
	port = "8080"
	restart_limit = 6
	timeout = "2s"